[project]
name = "media-organizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "piexif>=1.1.3",
    "pillow>=11.3.0",
    "pyqt6>=6.9.1",
    "tcl>=0.2",
]
